# Generated by Django 4.2.23 on 2026-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomrecord',
            name='final_diagnosis',
            field=models.CharField(blank=True, default='', help_text='Resolved final diagnosis (staff_diagnosis if set, otherwise predicted_disease)', max_length=200),
        ),
        migrations.AddField(
            model_name='symptomrecord',
            name='staff_diagnosis',
            field=models.CharField(blank=True, default='', help_text='Final diagnosis set by clinic staff, overrides AI prediction', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Clinic Staff')], default='student', help_text='User role (immutable)', max_length=10),
        ),
    ]
