# Generated by Django 4.2.23 on 2026-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_message_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomrecord',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, help_text='Patient age at time of report', null=True),
        ),
        migrations.AddField(
            model_name='symptomrecord',
            name='patient_sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', help_text='Patient biological sex', max_length=10),
        ),
    ]
