# Generated by Django 4.2.23 on 2026-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_symptomrecord_patient_age_symptomrecord_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for password resets', max_length=254, null=True, unique=True),
        ),
    ]
